name: dart_gsheets_api
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dotenv: ^3.0.0
  gsheets: ^0.3.0
  shelf: ^1.1.4
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
